package:
  name: openmvg
  version: 0.0

source:
  git_url: https://github.com/openMVG/openMVG.git
  git_rev: develop
  git_submodule: recursive

build:
  number: 0  # Increment this for subsequent builds
  binary_relocation: false # Don't need conda's relocation mechanism


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - eigen
    - boost-cpp
    - opencv
    - ceres-solver

  run: 
    # Add runtime dependencies here

host:
  # Linux
  linux-64:
    - gcc_linux-64
    - gxx_linux-64


about:
  home: https://github.com/openMVG/openMVG
  license: MPL-2.0

extra:
  recipe-maintainers:
    - sannat17
